### ISSUE TITLE
[WEB API Specification] Missing format for various 'type: number'

### ISSUE THREAD

**Issue by etiennerobaglia** [GroupePSA/groupepsa.github.io#46]
Format is not defined for `type: number` in Web API OpenAPI Specifcation.
**Example:**
```yaml
    VehicleOdometer:
        type: object
        properties:
          mileage:
                description: Vehicle mileage expressed in KM.
                type: number
          createdAt:
              type: string
              format: date-time
```
This lead to misfunctions with swagger's codegen feature (in particular with JAVA).
