### ISSUE TITLE
[WEB API Specification] Missing type in Geometry > coordinates

### ISSUE THREAD

**Issue by etiennerobaglia** [GroupePSA/groupepsa.github.io#49]
`coordinates` in Geometry schema is missing a `type: `:

```yaml

Geometry:
      title: Geometry
      type: object
      description: >-
        This object expresses the Geometry as specified by
        [rfc7946](https://tools.ietf.org/html/rfc7946#section-3.1). It is also
        the root of the Geometry objects (Point, cicle, poygon)
      properties:
        coordinates:
          title: Coordinates
          description: Geometry coordinates
```
